# Generated by Django 5.2.1 on 2025-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodtracker',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
