# Generated by Django 5.2.1 on 2025-05-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarathi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=40)),
                ('mobile_no', models.IntegerField()),
                ('stream', models.CharField(max_length=40)),
            ],
        ),
    ]
