# Generated by Django 5.2.1 on 2025-05-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarathi', '0002_biodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='dept',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='mobile_no',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='stream',
            field=models.CharField(max_length=50),
        ),
    ]
