# Generated by Django 5.2.1 on 2025-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarathi', '0003_alter_biodata_dept_alter_biodata_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
