# Generated by Django 5.2.1 on 2025-05-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarathi', '0004_alter_biodata_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
            ],
        ),
    ]
