# Generated by Django 5.2.1 on 2025-05-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarathi', '0005_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
